# Generated by scripts/render-formula.sh in lucassaldanha/tekops on every
# release. Edits here are overwritten by the next one.
class Tekops < Formula
  desc "Helper CLI for operating a Teku node"
  homepage "https://github.com/lucassaldanha/tekops"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    # No Intel macOS build is published.
    depends_on arch: :arm64

    url "https://github.com/lucassaldanha/tekops/releases/download/v0.11.0/tekops-v0.11.0-aarch64-macos.tar.gz"
    sha256 "a2a781badd4dcdadf79f2caebdc9807afa2dc9a6bc26e80160a9c1d23e4f1be8"
  end

  on_linux do
    on_intel do
      url "https://github.com/lucassaldanha/tekops/releases/download/v0.11.0/tekops-v0.11.0-x86_64-linux.tar.gz"
      sha256 "3432bc46af8781a76b1efd3ee64753719b4f311056e280f5f7a60ab3154f418a"
    end
    on_arm do
      url "https://github.com/lucassaldanha/tekops/releases/download/v0.11.0/tekops-v0.11.0-aarch64-linux.tar.gz"
      sha256 "a17ca85bd61852e3c3497223cfff61325a8ba57a45136a3aa238310d643bbcdf"
    end
  end

  def install
    bin.install "tekops"
    doc.install "USAGE.md"
    pkgshare.install "config.example.toml"
    generate_completions_from_executable(bin/"tekops", "autocomplete", "--print")
  end

  def caveats
    <<~EOS
      Update tekops with `brew upgrade tekops`; `tekops update` refuses to
      replace a Homebrew-managed binary.

      An example config file is at:
        #{pkgshare}/config.example.toml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tekops --version")
  end
end
